--- 
title: "Freeze d'un modèle"
author: "Géraud Dugé de Bernonville"
date: "29 septembre 2018"
output: html_document
---

```{r}
model_output_dir <- './target/models/'
saved_model_filename <- paste0(model_output_dir, 'hdf5')
```

# Freeze du modèle

```{r}
library(reticulate)
use_virtualenv('~/.virtualenvs/r-tensorflow-py3', required = TRUE)

library(keras)
library(tensorflow)
sess <- tf$Session()
k_set_session(sess)
k_set_learning_phase(0)

model <- load_model_hdf5(saved_model_filename)

config <- get_config(model)
weights <- get_weights(model)

# re-build a model where the learning phase is now hard-coded to 0
new_model <- from_config(config)
set_weights(new_model, weights)

input <- strsplit(new_model$input$name, ':')[[1]][1]
output <- strsplit(new_model$output$name, ':')[[1]][1]
Sys.setenv(INPUT_NAME = input,
           OUTPUT_NAME = output)

optimized_graph <- sess$graph$as_graph_def()
#optimized_graph <- tf$graph_util$remove_training_nodes(optimized_graph)
optimized_graph <- tf$graph_util$convert_variables_to_constants(sess, optimized_graph, list(output))


tf$train$write_graph(optimized_graph, model_output_dir, 'keras_to_tf.pb', as_text=FALSE)
tf$train$write_graph(optimized_graph, model_output_dir, 'keras_to_tf.txt', as_text=TRUE)

```

# Compilation vers le NCS

```{bash}
docker pull geraudster/ncs-container
```

On utilise `mvNCCompile` en spécifiant en  `r input` en input et `r output` en output:

```{bash}
mkdir -p $PWD/target/ncs
docker run -v $PWD/target/models/keras_to_tf.pb:/model.pb \
       	   -v $PWD/target/ncs:/output \
           -it geraudster/ncs-container \
               mvNCCompile /model.pb -o /output/ncs.pb \
	                   -in $INPUT_NAME -on $OUTPUT_NAME \
               || true
```
